CREATE TABLE players (
    steamid64 VARCHAR(17) PRIMARY KEY,
    player_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT null,
    total_kills INT DEFAULT 0,
    total_deaths INT DEFAULT 0,
    total_assists INT DEFAULT 0,
    total_wins INT DEFAULT 0,
    total_battles INT DEFAULT 0
);

CREATE TABLE weapon_types (
    weapon_id SERIAL PRIMARY KEY,
    weapon_name VARCHAR(50) NOT NULL
);

CREATE TABLE maps (
    map_id SERIAL PRIMARY KEY,
    map_name VARCHAR(50) NOT NULL
);


CREATE TABLE game_sessions (
    session_id SERIAL PRIMARY KEY,
    player_id VARCHAR(17) REFERENCES players(steamid64),
    map_id INT references maps(map_id),
    session_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_kills INT DEFAULT 0,
    total_deaths INT DEFAULT 0,
    total_assists INT DEFAULT 0,
    is_win BOOL DEFAULT false
);

CREATE TABLE session_weapons (
    session_id INT REFERENCES game_sessions(session_id),
    weapon_id INT REFERENCES weapon_types(weapon_id),
    kills INT DEFAULT 0,
    UNIQUE (session_id, weapon_id)
);

insert into weapon_types(weapon_name) values ('M16A4');
insert into weapon_types(weapon_name) values ('M4A1');
insert into weapon_types(weapon_name) values ('M27');
insert into weapon_types(weapon_name) values ('EF88');
insert into weapon_types(weapon_name) values ('L85A2');
insert into weapon_types(weapon_name) values ('L86A2');
insert into weapon_types(weapon_name) values ('Type-95');
insert into weapon_types(weapon_name) values ('Type-95 Carb');
insert into weapon_types(weapon_name) values ('AK74');
insert into weapon_types(weapon_name) values ('AK-12');
insert into weapon_types(weapon_name) values ('AKS-74u');
insert into weapon_types(weapon_name) values ('SVD');
insert into weapon_types(weapon_name) values ('Type-88 Gross');
insert into weapon_types(weapon_name) values ('M110 ');
insert into weapon_types(weapon_name) values ('HK417');
insert into weapon_types(weapon_name) values ('G3A3');
insert into weapon_types(weapon_name) values ('FN FAL');
insert into weapon_types(weapon_name) values ('HK-51');
insert into weapon_types(weapon_name) values ('SKS');
insert into weapon_types(weapon_name) values ('AKM');
insert into weapon_types(weapon_name) values ('AMD65');
insert into weapon_types(weapon_name) values ('ASVAL');
insert into weapon_types(weapon_name) values ('M249_Militia');
insert into weapon_types(weapon_name) values ('M249_US/AU');
insert into weapon_types(weapon_name) values ('Type 95 LMG');
insert into weapon_types(weapon_name) values ('L110A2');
insert into weapon_types(weapon_name) values ('RPK74 ');
insert into weapon_types(weapon_name) values ('Type-88 MG');
insert into weapon_types(weapon_name) values ('G3 MG');
insert into weapon_types(weapon_name) values ('RPK DRUM');
insert into weapon_types(weapon_name) values ('RPD');
insert into weapon_types(weapon_name) values ('PKM');
insert into weapon_types(weapon_name) values ('PKP');
insert into weapon_types(weapon_name) values ('L7A2');
insert into weapon_types(weapon_name) values ('M240B');
insert into weapon_types(weapon_name) values ('Maximi');
insert into weapon_types(weapon_name) values ('MG3');
insert into weapon_types(weapon_name) values ('Mosin Nugget');
insert into weapon_types(weapon_name) values ('Mosin Badbine');
insert into weapon_types(weapon_name) values ('C14 Guass Rifle');
insert into weapon_types(weapon_name) values ('SV98M');
insert into weapon_types(weapon_name) values ('PPSH');
insert into weapon_types(weapon_name) values ('Skorpion');
insert into weapon_types(weapon_name) values ('TT-33');
insert into weapon_types(weapon_name) values ('M9A1');
insert into weapon_types(weapon_name) values ('Browning P35');
insert into weapon_types(weapon_name) values ('MP-443');
insert into weapon_types(weapon_name) values ('L131A1');
insert into weapon_types(weapon_name) values ('M-17');
insert into weapon_types(weapon_name) values ('Makarov');
insert into weapon_types(weapon_name) values ('Type 92');
insert into weapon_types(weapon_name) values ('Browning Hi Powe');
insert into maps(map_name) values ('Anvil_AAS_v1');
insert into maps(map_name) values ('Anvil_AAS_v2');
insert into maps(map_name) values ('Anvil_Invasion_v1');
insert into maps(map_name) values ('Anvil_Invasion_v2');
insert into maps(map_name) values ('Anvil_RAAS_v1');
insert into maps(map_name) values ('Anvil_RAAS_v2');
insert into maps(map_name) values ('Anvil_RAAS_v3');
insert into maps(map_name) values ('Anvil_RAAS_v4');
insert into maps(map_name) values ('Anvil_Skirmish_v1');
insert into maps(map_name) values ('Anvil_TC_v1');
insert into maps(map_name) values ('AlBasrah_AAS_v1');
insert into maps(map_name) values ('AlBasrah_AAS_v2');
insert into maps(map_name) values ('AlBasrah_AAS_v3');
insert into maps(map_name) values ('AlBasrah_Insurgency_v1');
insert into maps(map_name) values ('AlBasrah_Invasion_v1');
insert into maps(map_name) values ('AlBasrah_Invasion_v2');
insert into maps(map_name) values ('AlBasrah_Invasion_v3');
insert into maps(map_name) values ('AlBasrah_Invasion_v4');
insert into maps(map_name) values ('AlBasrah_Invasion_v5');
insert into maps(map_name) values ('AlBasrah_Invasion_v6');
insert into maps(map_name) values ('AlBasrah_Invasion_v7');
insert into maps(map_name) values ('AlBasrah_Invasion_v8');
insert into maps(map_name) values ('AlBasrah_RAAS_v1');
insert into maps(map_name) values ('AlBasrah_Seed_v1');
insert into maps(map_name) values ('AlBasrah_Skirmish_v1');
insert into maps(map_name) values ('AlBasrah_Skirmish_v2');
insert into maps(map_name) values ('AlBasrah_TA_v1');
insert into maps(map_name) values ('AlBasrah_TC_v1');
insert into maps(map_name) values ('AlBasrah_TC_v2');
insert into maps(map_name) values ('Belaya_AAS_v1');
insert into maps(map_name) values ('Belaya_AAS_v2');
insert into maps(map_name) values ('Belaya_AAS_v3');
insert into maps(map_name) values ('Belaya_Invasion_v1');
insert into maps(map_name) values ('Belaya_Invasion_v2');
insert into maps(map_name) values ('Belaya_Invasion_v3');
insert into maps(map_name) values ('Belaya_RAAS_v1');
insert into maps(map_name) values ('Belaya_RAAS_v2');
insert into maps(map_name) values ('Belaya_RAAS_v3');
insert into maps(map_name) values ('Belaya_RAAS_v4');
insert into maps(map_name) values ('Belaya_RAAS_v5');
insert into maps(map_name) values ('Belaya_Skirmish_v1');
insert into maps(map_name) values ('Belaya_TC_v1');
insert into maps(map_name) values ('Chora_AAS_v1');
insert into maps(map_name) values ('Chora_AAS_v2');
insert into maps(map_name) values ('Chora_AAS_v3');
insert into maps(map_name) values ('Chora_AAS_v4');
insert into maps(map_name) values ('Chora_AAS_v5');
insert into maps(map_name) values ('Chora_AAS_v6');
insert into maps(map_name) values ('Chora_Insurgency_v1');
insert into maps(map_name) values ('Chora_Invasion_v1');
insert into maps(map_name) values ('Chora_Invasion_v2');
insert into maps(map_name) values ('Chora_RAAS_v1');
insert into maps(map_name) values ('Chora_RAAS_v2');
insert into maps(map_name) values ('Chora_RAAS_v3');
insert into maps(map_name) values ('Chora_RAAS_v4');
insert into maps(map_name) values ('Chora_RAAS_v5');
insert into maps(map_name) values ('Chora_Skirmish_v1');
insert into maps(map_name) values ('Chora_TC_v1');
insert into maps(map_name) values ('Fallujah_AAS_v1');
insert into maps(map_name) values ('Fallujah_AAS_v2');
insert into maps(map_name) values ('Fallujah_Insurgency_v1');
insert into maps(map_name) values ('Fallujah_Invasion_v1');
insert into maps(map_name) values ('Fallujah_Invasion_v2');
insert into maps(map_name) values ('Fallujah_Invasion_v3');
insert into maps(map_name) values ('Fallujah_Invasion_v4');
insert into maps(map_name) values ('Fallujah_Invasion_v5');
insert into maps(map_name) values ('Fallujah_Invasion_v6');
insert into maps(map_name) values ('Fallujah_RAAS_v1');
insert into maps(map_name) values ('Fallujah_RAAS_v2');
insert into maps(map_name) values ('Fallujah_RAAS_v3');
insert into maps(map_name) values ('Fallujah_RAAS_v4');
insert into maps(map_name) values ('Fallujah_RAAS_v5');
insert into maps(map_name) values ('Fallujah_RAAS_v6');
insert into maps(map_name) values ('Fallujah_RAAS_v7');
insert into maps(map_name) values ('Fallujah_Seed_v1');
insert into maps(map_name) values ('Fallujah_Skirmish_v1');
insert into maps(map_name) values ('Fallujah_Skirmish_v2');
insert into maps(map_name) values ('Fallujah_TC_v1');
insert into maps(map_name) values ('Fallujah_TC_v2');
insert into maps(map_name) values ('FoolsRoad_AAS_v1');
insert into maps(map_name) values ('FoolsRoad_AAS_v2');
insert into maps(map_name) values ('FoolsRoad_Destruction_v1');
insert into maps(map_name) values ('FoolsRoad_Invasion_v1');
insert into maps(map_name) values ('FoolsRoad_RAAS_v1');
insert into maps(map_name) values ('FoolsRoad_RAAS_v2');
insert into maps(map_name) values ('FoolsRoad_RAAS_v3');
insert into maps(map_name) values ('FoolsRoad_RAAS_v4');
insert into maps(map_name) values ('FoolsRoad_RAAS_v5');
insert into maps(map_name) values ('FoolsRoad_Skirmish_v1');
insert into maps(map_name) values ('FoolsRoad_Skirmish_v2');
insert into maps(map_name) values ('FoolsRoad_TC_v1');
insert into maps(map_name) values ('GooseBay_AAS_v1');
insert into maps(map_name) values ('GooseBay_AAS_v2');
insert into maps(map_name) values ('GooseBay_Invasion_v1');
insert into maps(map_name) values ('GooseBay_Invasion_v2');
insert into maps(map_name) values ('GooseBay_Invasion_v3');
insert into maps(map_name) values ('GooseBay_Invasion_v4');
insert into maps(map_name) values ('GooseBay_Invasion_v5');
insert into maps(map_name) values ('GooseBay_RAAS_v1');
insert into maps(map_name) values ('GooseBay_RAAS_v2');
insert into maps(map_name) values ('GooseBay_RAAS_v3');
insert into maps(map_name) values ('GooseBay_RAAS_v4');
insert into maps(map_name) values ('GooseBay_Seed_v1');
insert into maps(map_name) values ('GooseBay_Skirmish_v1');
insert into maps(map_name) values ('Gorodok_AAS_v1');
insert into maps(map_name) values ('Gorodok_AAS_v2');
insert into maps(map_name) values ('Gorodok_AAS_v3');
insert into maps(map_name) values ('Gorodok_AAS_v4');
insert into maps(map_name) values ('Gorodok_Destruction_v1');
insert into maps(map_name) values ('Gorodok_Insurgency_v1');
insert into maps(map_name) values ('Gorodok_Invasion_v1');
insert into maps(map_name) values ('Gorodok_Invasion_v2');
insert into maps(map_name) values ('Gorodok_Invasion_v3');
insert into maps(map_name) values ('Gorodok_RAAS_v01');
insert into maps(map_name) values ('Gorodok_RAAS_v02');
insert into maps(map_name) values ('Gorodok_RAAS_v03');
insert into maps(map_name) values ('Gorodok_RAAS_v04');
insert into maps(map_name) values ('Gorodok_RAAS_v05');
insert into maps(map_name) values ('Gorodok_RAAS_v06');
insert into maps(map_name) values ('Gorodok_RAAS_v07');
insert into maps(map_name) values ('Gorodok_RAAS_v08');
insert into maps(map_name) values ('Gorodok_RAAS_v09');
insert into maps(map_name) values ('Gorodok_RAAS_v10');
insert into maps(map_name) values ('Gorodok_RAAS_v11');
insert into maps(map_name) values ('Gorodok_RAAS_v12');
insert into maps(map_name) values ('Gorodok_Skirmish_v1');
insert into maps(map_name) values ('Gorodok_TC_v1');
insert into maps(map_name) values ('Gorodok_TC_v2');
insert into maps(map_name) values ('Kamdesh_AAS_v1');
insert into maps(map_name) values ('Kamdesh_Insurgency_v1');
insert into maps(map_name) values ('Kamdesh_Insurgency_v2');
insert into maps(map_name) values ('Kamdesh_Invasion_v1');
insert into maps(map_name) values ('Kamdesh_Invasion_v2');
insert into maps(map_name) values ('Kamdesh_Invasion_v3');
insert into maps(map_name) values ('Kamdesh_Invasion_v4');
insert into maps(map_name) values ('Kamdesh_Invasion_v5');
insert into maps(map_name) values ('Kamdesh_Invasion_v6');
insert into maps(map_name) values ('Kamdesh_Invasion_v7');
insert into maps(map_name) values ('Kamdesh_RAAS_v1');
insert into maps(map_name) values ('Kamdesh_RAAS_v2');
insert into maps(map_name) values ('Kamdesh_RAAS_v3');
insert into maps(map_name) values ('Kamdesh_RAAS_v4');
insert into maps(map_name) values ('Kamdesh_RAAS_v5');
insert into maps(map_name) values ('Kamdesh_RAAS_v6');
insert into maps(map_name) values ('Kamdesh_RAAS_v7');
insert into maps(map_name) values ('Kamdesh_Skirmish_v1');
insert into maps(map_name) values ('Kamdesh_TC_v1');
insert into maps(map_name) values ('Kamdesh_TC_v2');
insert into maps(map_name) values ('Kamdesh_TC_v3');
insert into maps(map_name) values ('Kamdesh_TC_v4');
insert into maps(map_name) values ('Kohat_AAS_v1');
insert into maps(map_name) values ('Kohat_AAS_v2');
insert into maps(map_name) values ('Kohat_AAS_v3');
insert into maps(map_name) values ('Kohat_Insurgency_v1');
insert into maps(map_name) values ('Kohat_Invasion_v1');
insert into maps(map_name) values ('Kohat_Invasion_v2');
insert into maps(map_name) values ('Kohat_Invasion_v3');
insert into maps(map_name) values ('Kohat_Invasion_v4');
insert into maps(map_name) values ('Kohat_RAAS_v01');
insert into maps(map_name) values ('Kohat_RAAS_v02');
insert into maps(map_name) values ('Kohat_RAAS_v03');
insert into maps(map_name) values ('Kohat_RAAS_v04');
insert into maps(map_name) values ('Kohat_RAAS_v05');
insert into maps(map_name) values ('Kohat_RAAS_v06');
insert into maps(map_name) values ('Kohat_RAAS_v07');
insert into maps(map_name) values ('Kohat_RAAS_v08');
insert into maps(map_name) values ('Kohat_RAAS_v09');
insert into maps(map_name) values ('Kohat_RAAS_v10');
insert into maps(map_name) values ('Kohat_Skirmish_v1');
insert into maps(map_name) values ('Kohat_TC_v1');
insert into maps(map_name) values ('Kokan_AAS_v1');
insert into maps(map_name) values ('Kokan_AAS_v2');
insert into maps(map_name) values ('Kokan_AAS_v3');
insert into maps(map_name) values ('Kokan_Insurgency_v1');
insert into maps(map_name) values ('Kokan_Invasion_v1');
insert into maps(map_name) values ('Kokan_RAAS_v1');
insert into maps(map_name) values ('Kokan_RAAS_v2');
insert into maps(map_name) values ('Kokan_RAAS_v3');
insert into maps(map_name) values ('Kokan_RAAS_v4');
insert into maps(map_name) values ('Kokan_Skirmish_v1');
insert into maps(map_name) values ('Kokan_TC_v1');
insert into maps(map_name) values ('Lashkar_AAS_v1');
insert into maps(map_name) values ('Lashkar_AAS_v2');
insert into maps(map_name) values ('Lashkar_AAS_v3');
insert into maps(map_name) values ('Lashkar_AAS_v4');
insert into maps(map_name) values ('Lashkar_Insurgency_v1');
insert into maps(map_name) values ('Lashkar_Invasion_v1');
insert into maps(map_name) values ('Lashkar_Invasion_v2');
insert into maps(map_name) values ('Lashkar_Invasion_v3');
insert into maps(map_name) values ('Lashkar_Invasion_v4');
insert into maps(map_name) values ('Lashkar_RAAS_v1');
insert into maps(map_name) values ('Lashkar_RAAS_v2');
insert into maps(map_name) values ('Lashkar_RAAS_v3');
insert into maps(map_name) values ('Lashkar_RAAS_v4');
insert into maps(map_name) values ('Lashkar_RAAS_v5');
insert into maps(map_name) values ('Lashkar_Skirmish_v1');
insert into maps(map_name) values ('Lashkar_TC_v1');
insert into maps(map_name) values ('Lashkar_TC_v2');
insert into maps(map_name) values ('Lashkar_TC_v3');
insert into maps(map_name) values ('Lashkar_TC_v4');
insert into maps(map_name) values ('Lashkar_TC_v5');
insert into maps(map_name) values ('Logar_AAS_v1');
insert into maps(map_name) values ('Logar_AAS_v2');
insert into maps(map_name) values ('Logar_AAS_v3');
insert into maps(map_name) values ('Logar_Insurgency_v1');
insert into maps(map_name) values ('Logar_RAAS_v1');
insert into maps(map_name) values ('Logar_RAAS_v2');
insert into maps(map_name) values ('Logar_Seed_v1');
insert into maps(map_name) values ('Logar_Skirmish_v1');
insert into maps(map_name) values ('Logar_TC_v1');
insert into maps(map_name) values ('Manicouagan_AAS_v1');
insert into maps(map_name) values ('Manicouagan_AAS_v2');
insert into maps(map_name) values ('Manicouagan_AAS_v3');
insert into maps(map_name) values ('Manicouagan_AAS_v4');
insert into maps(map_name) values ('Manicouagan_AAS_v5');
insert into maps(map_name) values ('Manicouagan_Invasion_v1');
insert into maps(map_name) values ('Manicouagan_Invasion_v2');
insert into maps(map_name) values ('Manicouagan_Invasion_v3');
insert into maps(map_name) values ('Manicouagan_Invasion_v4');
insert into maps(map_name) values ('Manicouagan_Invasion_v5');
insert into maps(map_name) values ('Manicouagan_Invasion_v6');
insert into maps(map_name) values ('Manicouagan_Invasion_v7');
insert into maps(map_name) values ('Manicouagan_Invasion_v8');
insert into maps(map_name) values ('Manicouagan_Invasion_v9');
insert into maps(map_name) values ('Manicouagan_RAAS_v1');
insert into maps(map_name) values ('Manicouagan_RAAS_v10');
insert into maps(map_name) values ('Manicouagan_RAAS_v11');
insert into maps(map_name) values ('Manicouagan_RAAS_v12');
insert into maps(map_name) values ('Manicouagan_RAAS_v13');
insert into maps(map_name) values ('Manicouagan_RAAS_v14');
insert into maps(map_name) values ('Manicouagan_RAAS_v15');
insert into maps(map_name) values ('Manicouagan_RAAS_v2');
insert into maps(map_name) values ('Manicouagan_RAAS_v3');
insert into maps(map_name) values ('Manicouagan_RAAS_v4');
insert into maps(map_name) values ('Manicouagan_RAAS_v5');
insert into maps(map_name) values ('Manicouagan_RAAS_v6');
insert into maps(map_name) values ('Manicouagan_RAAS_v7');
insert into maps(map_name) values ('Manicouagan_RAAS_v8');
insert into maps(map_name) values ('Manicouagan_RAAS_v9');
insert into maps(map_name) values ('Manicouagan_Seed_v1');
insert into maps(map_name) values ('Manicouagan_Skirmish_v1');
insert into maps(map_name) values ('Manicouagan_Skirmish_v2');
insert into maps(map_name) values ('Manicouagan_Skirmish_v3');
insert into maps(map_name) values ('Mestia_AAS_v1');
insert into maps(map_name) values ('Mestia_AAS_v2');
insert into maps(map_name) values ('Mestia_Invasion_v1');
insert into maps(map_name) values ('Mestia_Invasion_v2');
insert into maps(map_name) values ('Mestia_RAAS_v1');
insert into maps(map_name) values ('Mestia_RAAS_v2');
insert into maps(map_name) values ('Mestia_Skirmish_v1');
insert into maps(map_name) values ('Mestia_TC_v1');
insert into maps(map_name) values ('Mutaha_AAS_v1');
insert into maps(map_name) values ('Mutaha_AAS_v2');
insert into maps(map_name) values ('Mutaha_AAS_v3');
insert into maps(map_name) values ('Mutaha_AAS_v4');
insert into maps(map_name) values ('Mutaha_Invasion_v1');
insert into maps(map_name) values ('Mutaha_Invasion_v2');
insert into maps(map_name) values ('Mutaha_Invasion_v3');
insert into maps(map_name) values ('Mutaha_Invasion_v4');
insert into maps(map_name) values ('Mutaha_RAAS_v1');
insert into maps(map_name) values ('Mutaha_RAAS_v2');
insert into maps(map_name) values ('Mutaha_RAAS_v3');
insert into maps(map_name) values ('Mutaha_RAAS_v4');
insert into maps(map_name) values ('Mutaha_RAAS_v5');
insert into maps(map_name) values ('Mutaha_RAAS_v6');
insert into maps(map_name) values ('Mutaha_RAAS_v7');
insert into maps(map_name) values ('Mutaha_Seed_v1');
insert into maps(map_name) values ('Mutaha_Skirmish_v1');
insert into maps(map_name) values ('Mutaha_Tanks_v1');
insert into maps(map_name) values ('Mutaha_TC_v1');
insert into maps(map_name) values ('Mutaha_TC_v2');
insert into maps(map_name) values ('Narva_AAS_v1');
insert into maps(map_name) values ('Narva_AAS_v2');
insert into maps(map_name) values ('Narva_AAS_v3');
insert into maps(map_name) values ('Narva_AAS_v4');
insert into maps(map_name) values ('Narva_Destruction_v1');
insert into maps(map_name) values ('Narva_Invasion_v1');
insert into maps(map_name) values ('Narva_Invasion_v2');
insert into maps(map_name) values ('Narva_Invasion_v3');
insert into maps(map_name) values ('Narva_Invasion_v4');
insert into maps(map_name) values ('Narva_Invasion_v5');
insert into maps(map_name) values ('Narva_RAAS_v1');
insert into maps(map_name) values ('Narva_RAAS_v2');
insert into maps(map_name) values ('Narva_RAAS_v3');
insert into maps(map_name) values ('Narva_RAAS_v4');
insert into maps(map_name) values ('Narva_RAAS_v5');
insert into maps(map_name) values ('Narva_RAAS_v6');
insert into maps(map_name) values ('Narva_RAAS_v7');
insert into maps(map_name) values ('Narva_Skirmish_v1');
insert into maps(map_name) values ('Narva_TA_v1');
insert into maps(map_name) values ('Narva_TC_v1');
insert into maps(map_name) values ('Narva_TC_v2');
insert into maps(map_name) values ('Skorpo_AAS_v1');
insert into maps(map_name) values ('Skorpo_Invasion_v1');
insert into maps(map_name) values ('Skorpo_Invasion_v2');
insert into maps(map_name) values ('Skorpo_Invasion_v3');
insert into maps(map_name) values ('Skorpo_Invasion_v4');
insert into maps(map_name) values ('Skorpo_RAAS_v1');
insert into maps(map_name) values ('Skorpo_RAAS_v2');
insert into maps(map_name) values ('Skorpo_RAAS_v3');
insert into maps(map_name) values ('Skorpo_RAAS_v4');
insert into maps(map_name) values ('Skorpo_RAAS_v5');
insert into maps(map_name) values ('Skorpo_Skirmish_v1');
insert into maps(map_name) values ('Skorpo_TC_v1');
insert into maps(map_name) values ('Skorpo_TC_v2');
insert into maps(map_name) values ('Skorpo_TC_v3');
insert into maps(map_name) values ('Sumari_AAS_v1');
insert into maps(map_name) values ('Sumari_AAS_v2');
insert into maps(map_name) values ('Sumari_AAS_v3');
insert into maps(map_name) values ('Sumari_AAS_v4');
insert into maps(map_name) values ('Sumari_AAS_v5');
insert into maps(map_name) values ('Sumari_Insurgency_v1');
insert into maps(map_name) values ('Sumari_Invasion_v1');
insert into maps(map_name) values ('Sumari_RAAS_v1');
insert into maps(map_name) values ('Sumari_RAAS_v2');
insert into maps(map_name) values ('Sumari_Seed_v1');
insert into maps(map_name) values ('Sumari_Seed_v2');
insert into maps(map_name) values ('Sumari_Seed_v3');
insert into maps(map_name) values ('Sumari_Skirmish_v1');
insert into maps(map_name) values ('Sumari_TC_v1');
insert into maps(map_name) values ('Tallil_AAS_v1');
insert into maps(map_name) values ('Tallil_AAS_v2');
insert into maps(map_name) values ('Tallil_Invasion_v1');
insert into maps(map_name) values ('Tallil_Invasion_v2');
insert into maps(map_name) values ('Tallil_Invasion_v3');
insert into maps(map_name) values ('Tallil_Invasion_v4');
insert into maps(map_name) values ('Tallil_Invasion_v5');
insert into maps(map_name) values ('Tallil_RAAS_v1');
insert into maps(map_name) values ('Tallil_RAAS_v2');
insert into maps(map_name) values ('Tallil_RAAS_v3');
insert into maps(map_name) values ('Tallil_RAAS_v4');
insert into maps(map_name) values ('Tallil_RAAS_v5');
insert into maps(map_name) values ('Tallil_RAAS_v6');
insert into maps(map_name) values ('Tallil_RAAS_v7');
insert into maps(map_name) values ('Tallil_RAAS_v8');
insert into maps(map_name) values ('Tallil_Seed_v1');
insert into maps(map_name) values ('Tallil_Seed_v2');
insert into maps(map_name) values ('Tallil_Skirmish_v1');
insert into maps(map_name) values ('Tallil_Skirmish_v2');
insert into maps(map_name) values ('Tallil_Skirmish_v3');
insert into maps(map_name) values ('Tallil_Tanks_v1');
insert into maps(map_name) values ('Tallil_Tanks_v2');
insert into maps(map_name) values ('Tallil_TA_v1');
insert into maps(map_name) values ('Tallil_Outskirts_TC_v1');
insert into maps(map_name) values ('Yehorivka_AAS_v1');
insert into maps(map_name) values ('Yehorivka_AAS_v2');
insert into maps(map_name) values ('Yehorivka_AAS_v3');
insert into maps(map_name) values ('Yehorivka_AAS_v4');
insert into maps(map_name) values ('Yehorivka_Destruction_v1');
insert into maps(map_name) values ('Yehorivka_Invasion_v1');
insert into maps(map_name) values ('Yehorivka_Invasion_v2');
insert into maps(map_name) values ('Yehorivka_Invasion_v3');
insert into maps(map_name) values ('Yehorivka_RAAS_v01');
insert into maps(map_name) values ('Yehorivka_RAAS_v02');
insert into maps(map_name) values ('Yehorivka_RAAS_v03');
insert into maps(map_name) values ('Yehorivka_RAAS_v04');
insert into maps(map_name) values ('Yehorivka_RAAS_v05');
insert into maps(map_name) values ('Yehorivka_RAAS_v06');
insert into maps(map_name) values ('Yehorivka_RAAS_v07');
insert into maps(map_name) values ('Yehorivka_RAAS_v08');
insert into maps(map_name) values ('Yehorivka_RAAS_v09');
insert into maps(map_name) values ('Yehorivka_RAAS_v10');
insert into maps(map_name) values ('Yehorivka_RAAS_v11');
insert into maps(map_name) values ('Yehorivka_RAAS_v12');
insert into maps(map_name) values ('Yehorivka_RAAS_v13');
insert into maps(map_name) values ('Yehorivka_RAAS_v14');
insert into maps(map_name) values ('Yehorivka_Skirmish_v1');
insert into maps(map_name) values ('Yehorivka_Skirmish_v2');
insert into maps(map_name) values ('Yehorivka_Skirmish_v3');
insert into maps(map_name) values ('Yehorivka_TA_v1');
insert into maps(map_name) values ('Yehorivka_TC_v1');
insert into maps(map_name) values ('Yehorivka_TC_v2');
insert into maps(map_name) values ('Yehorivka_TC_v3');
insert into maps(map_name) values ('BlackCoast_AAS_v1');
insert into maps(map_name) values ('BlackCoast_AAS_v2');
insert into maps(map_name) values ('BlackCoast_Invasion_v1');
insert into maps(map_name) values ('BlackCoast_Invasion_v2');
insert into maps(map_name) values ('BlackCoast_Invasion_v3');
insert into maps(map_name) values ('BlackCoast_Invasion_v4');
insert into maps(map_name) values ('BlackCoast_Invasion_v5');
insert into maps(map_name) values ('BlackCoast_RAAS_v1');
insert into maps(map_name) values ('BlackCoast_RAAS_v2');
insert into maps(map_name) values ('BlackCoast_RAAS_v3');
insert into maps(map_name) values ('BlackCoast_RAAS_v4');
insert into maps(map_name) values ('BlackCoast_RAAS_v5');
insert into maps(map_name) values ('BlackCoast_Seed_v1');
insert into maps(map_name) values ('BlackCoast_Skirmish_v1');
insert into maps(map_name) values ('Harju_AAS_v1');
insert into maps(map_name) values ('Harju_AAS_v2');
insert into maps(map_name) values ('Harju_AAS_v3');
insert into maps(map_name) values ('Harju_Invasion_v1');
insert into maps(map_name) values ('Harju_Invasion_v2');
insert into maps(map_name) values ('Harju_Invasion_v3');
insert into maps(map_name) values ('Harju_Invasion_v4');
insert into maps(map_name) values ('Harju_Invasion_v5');
insert into maps(map_name) values ('Harju_RAAS_v1');
insert into maps(map_name) values ('Harju_RAAS_v2');
insert into maps(map_name) values ('Harju_RAAS_v3');
insert into maps(map_name) values ('Harju_RAAS_v4');
insert into maps(map_name) values ('Harju_RAAS_v5');
insert into maps(map_name) values ('Harju_RAAS_v6');
insert into maps(map_name) values ('Harju_Seed_v1');
insert into maps(map_name) values ('Harju_Skirmish_v1');
insert into maps(map_name) values ('Harju_Skirmish_v2');
